# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "/uploads/" # Folder where user uploaded files should go

# publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # PAGES
  - label: "Seiten"
    name: "seiten"
    editor:
      preview: false
    files:
      - label: "Geschichte des Ortes"
        name: "geschichte"
        file: "_pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Über uns"
        name: "ueber-uns"
        file: "_pages/ueber-uns.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      #- label: "Bilddokumentation"
      #  name: "bilddoku"
      #  file: "_pages/bilddokumentation.md"
      #  fields:
      #    - {label: "Layout", name: "layout", widget: "hidden", default: "bilddokumentation"}
      #    - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      #    - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "contact"
        name: "contact"
        file: "_pages/contact.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Datenschutz"
        name: "datenschutz"
        file: "_pages/datenschutz.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "bilddokumentation"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Impressum"
        name: "impressum"
        file: "_pages/impressum.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "bilddokumentation"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      
  # teaching
  - name: "teaching" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "teaching" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    filter: {field: "categories", value: "teaching"}
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Category", name: "categories", widget: "hidden", default: "teaching"}
      #- {label: "Image (/images/name-des-bildes.jpg)", name: "image", widget: "string", required: false}
      - {label: "teaching/teaching", name: "vaak", widget: "select", options: ["teaching", "teaching"], required: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      #- {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      #- {label: "Categories", name: "categories", widget: "string", required: false}
      - label: 'Audiomitschnitte'
        name: 'Audiomitschnitt'
        widget: 'list'
        fields:
          - { label: 'Titel', name: 'mp3-title', widget: 'string' }
          - { label: 'MP3', name: 'mp3', widget: 'file' }
      - label: 'PDFs'
        name: 'PDF'
        widget: 'list'
        fields:
          - { label: 'Titel', name: 'pdf-title', widget: 'string' }
          - { label: 'PDF Datei', name: 'pdf-file', widget: 'file' }
  # Dokumentation
  - name: "dokumentation" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Dokumentation" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    filter: {field: "categories", value: "dokumentation"}
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Category", name: "categories", widget: "hidden", default: "dokumentation"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      #- {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: 'Audiomitschnitte'
        name: 'Audiomitschnitt'
        widget: 'list'
        fields:
          - { label: 'Titel', name: 'mp3-title', widget: 'string' }
          - { label: 'MP3', name: 'mp3', widget: 'file' }
      - label: 'PDFs'
        name: 'PDF'
        widget: 'list'
        fields:
          - { label: 'Titel', name: 'pdf-title', widget: 'string' }
          - { label: 'PDF Datei', name: 'pdf-file', widget: 'file' }
